[theme]
primaryColor = "#4CAF50"             # accent color for buttons, sliders
backgroundColor = "#f0f2f6"          # main page background
secondaryBackgroundColor = "#ffffff" # sidebar & card backgrounds
textColor = "#111111"                # default text color
font = "sans serif"                  # options: "serif", "monospace"
